### ISSUE TITLE
Add Support to Use Custom Bucket Repo ?

### ISSUE THREAD

**Issue by Jvcon** [JamJar00/dotbot-scoop#1]
eg:

```
scoop:
  bukcet:
    - name: custom
      repo: 'https://github.com/*'
```

**Comment by JamJar00** [comment]
Definitely a good idea. I made a start on this on the feature/bucket-urls branch but it's not quite working yet. Will try and pick it up again over the next few days

**Comment by JamJar00** [comment]
Added in #2, let me know if there's any issues!
